# Generated by Django 5.0.2 on 2024-02-21 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'event_table',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('maincategory_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('maincategory_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'maincategory_table',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcategory_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=100)),
                ('maincategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='admin_app.maincategory')),
            ],
            options={
                'db_table': 'subcategory_table',
            },
        ),
    ]
