# Generated by Django 5.0.2 on 2024-02-21 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('license_number', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
            options={
                'db_table': 'seller_table',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('created_date', models.DateField(auto_now=True, null=True)),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.subcategory')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_app.seller')),
            ],
            options={
                'db_table': 'product_table',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('discount', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.event')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='seller_app.product')),
            ],
            options={
                'db_table': 'offer_table',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('mobile_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('battery', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='seller_app.product')),
            ],
            options={
                'db_table': 'mobile_table',
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('laptop_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('battery', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_app.product')),
            ],
            options={
                'db_table': 'laptop_table',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seller_app.product')),
            ],
            options={
                'db_table': 'image_table',
            },
        ),
        migrations.CreateModel(
            name='Headphone',
            fields=[
                ('headphone_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=100)),
                ('sound_output', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('battery', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headphone', to='seller_app.product')),
            ],
            options={
                'db_table': 'headphone_table',
            },
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('tv_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=100)),
                ('sound_output', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('warranty', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv', to='seller_app.product')),
            ],
            options={
                'db_table': 'tv_table',
            },
        ),
    ]
