# Generated by Django 5.0.2 on 2024-02-21 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('house_name', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('post_office', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
            ],
            options={
                'db_table': 'address_table',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=100)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('review', models.TextField(max_length=500)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='seller_app.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
            options={
                'db_table': 'review_table',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('order_date', models.DateField(auto_now=True, null=True)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.address')),
                ('offer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_app.offer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_app.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
            options={
                'db_table': 'order_table',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='seller_app.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
            options={
                'db_table': 'cart_table',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='seller_app.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
            options={
                'db_table': 'wishlist_table',
            },
        ),
    ]
